### ISSUE TITLE
start issue

### ISSUE THREAD

**Issue by Matrenuzz** [epic-miner/fooocus-lightning-ai#1]
whenever you close the studio on lightning and try to run the start sh script and port forward it again the web ui doesn't show up

**Comment by epic-miner** [comment]
ok i updated the scrpyt and i will make vedio for that update 
![Screenshot 2024-07-18 101016](https://github.com/user-attachments/assets/eef0d2cd-0852-4d02-8730-f86e70d11053)
when fooocus start up scroll up just a little bit and then you will see url click on that to access the fooocus
